### ISSUE TITLE
Game should not end after 3 rounds.

### ISSUE THREAD

**Issue by ElectricCoffee** [mcdemarco/cascades#1]
I had a thorough read through the rules and even asked in the original 2011 Cascades thread on BGG [[link](https://boardgamegeek.com/thread/682107/article/36971119#36971119)] and found that the game doesn't end after just three rounds. You're indeed supposed to just keep playing until you either win or run out of legal moves. 

The only bearing on the rules the round has, is which of the three extra draw-piles get turned over.
After those first three, no more get turned over, but the game continues.

**Comment by mcdemarco** [comment]
Fixed in [1.0.1](https://github.com/mcdemarco/cascades/releases/tag/v1.0.1), thanks!

**Comment by ElectricCoffee** [comment]
Sweet, will this update also be pushed to the version hosted on your website?

**Comment by mcdemarco** [comment]
> Sweet, will this update also be pushed to the version hosted on your website?

It should already be there.  There's no appcache to cause unusual caching of the old version (though there ought to be one).  It still tells you which round you're on, even though it doesn't matter; the only superficial difference is viewport changes on some mobile devices.

**Comment by ElectricCoffee** [comment]
Yeah it was a caching issue. When I last tried it, it still capped me at three rounds, but now that I've reloaded without cache, it correctly says "unlimited rounds".

For some reason, this version is significantly slower than the old one, taking about a second or so to respond to a click, where the old was instant.

**Comment by mcdemarco** [comment]
That's odd.  I don't think the removal of the round restriction could cause that by itself.  Are you playing on a mobile [touch] device?
